CREATE DATABASE SENTRY;

USE SENTRY;

CREATE TABLE USUARIO(
CPF CHAR(11) PRIMARY KEY,
EMAIL VARCHAR(255) UNIQUE NOT NULL,
NOME VARCHAR(255) NOT NULL,
AVATAR INT,
DESPESAS FLOAT DEFAULT 0
);

CREATE TABLE ARMAZENAMENTO(
ARMAZENAMENTOID INTEGER PRIMARY KEY,
NOME VARCHAR(255) NOT NULL,
USUARIO_CPF CHAR(11),
CONSTRAINT FK_USUARIO_CPF FOREIGN KEY (USUARIO_CPF) REFERENCES USUARIO(CPF)
);

CREATE TABLE PRODUTO(
PRODUTOID INTEGER PRIMARY KEY,
NOME VARCHAR(255) NOT NULL,
VALIDADE DATE NOT NULL,
QUANTIDADE FLOAT,
UNIDADE VARCHAR(50),
PRECO FLOAT,
ARMAZENAMENTOID INTEGER,
CONSTRAINT FK_ARMAZENAMENTOID FOREIGN KEY (ARMAZENAMENTOID) REFERENCES ARMAZENAMENTO(ARMAZENAMENTOID)
);

CREATE TABLE MOVIMENTACAO_FINANCEIRA(
MOVIMENTACAOID INTEGER PRIMARY KEY AUTO_INCREMENT,
VALOR FLOAT NOT NULL,
DESCRICAO VARCHAR(255),
TIPO ENUM('ENTRADA', 'SAIDA') NOT NULL,
DATA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DELIMITER //

CREATE TRIGGER TR_ESTOQUE_MINIMO
BEFORE UPDATE ON PRODUTO
FOR EACH ROW
BEGIN
    IF NEW.QUANTIDADE < 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ESTOQUE INSUFICIENTE';
    END IF;
END//

CREATE TRIGGER TR_ATUALIZAR_DESPESAS
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN
    IF NEW.QUANTIDADE < OLD.QUANTIDADE THEN
        UPDATE USUARIO
        SET DESPESAS = DESPESAS + ((OLD.QUANTIDADE - NEW.QUANTIDADE) * NEW.PRECO)
        WHERE CPF = (SELECT USUARIO_CPF FROM ARMAZENAMENTO WHERE ARMAZENAMENTOID = NEW.ARMAZENAMENTOID);
    END IF;
END//

CREATE PROCEDURE SP_MOVIMENTAR_ESTOQUE(
IN P_PRODUTOID INTEGER,
IN P_QUANTIDADE FLOAT
)
BEGIN
    UPDATE PRODUTO
    SET QUANTIDADE = QUANTIDADE + P_QUANTIDADE
    WHERE PRODUTOID = P_PRODUTOID;
END//

CREATE PROCEDURE SP_ITENS_MAIS_SAIDAS()
BEGIN
    SELECT NOME, QUANTIDADE
    FROM PRODUTO
    WHERE QUANTIDADE < 5
    ORDER BY QUANTIDADE ASC;
END//

CREATE PROCEDURE SP_MAIORES_GASTOS()
BEGIN
    SELECT DESCRICAO, VALOR
    FROM MOVIMENTACAO_FINANCEIRA
    WHERE TIPO = 'SAIDA'
    ORDER BY VALOR DESC;
END//

CREATE PROCEDURE SP_PRODUTOS_MAIS_CONSUMIDOS()
BEGIN
    SELECT P.NOME, A.NOME AS LOCAL_ARMAZENAMENTO
    FROM PRODUTO P
    JOIN ARMAZENAMENTO A ON P.ARMAZENAMENTOID = A.ARMAZENAMENTOID
    ORDER BY P.QUANTIDADE ASC;
END//

CREATE PROCEDURE SP_ATUALIZAR_PRECO_PRODUTO(
IN P_PRODUTOID INTEGER,
IN P_PRECO FLOAT
)
BEGIN
    UPDATE PRODUTO
    SET PRECO = P_PRECO
    WHERE PRODUTOID = P_PRODUTOID;
END//

CREATE PROCEDURE SP_COMPRAR_PRODUTO(
IN P_PRODUTOID INTEGER,
IN P_QUANTIDADE FLOAT
)
BEGIN
    DECLARE V_PRECO FLOAT;
    DECLARE V_NOME VARCHAR(255);
    DECLARE V_VALOR_TOTAL FLOAT;

    SELECT PRECO, NOME INTO V_PRECO, V_NOME
    FROM PRODUTO
    WHERE PRODUTOID = P_PRODUTOID;

    SET V_VALOR_TOTAL = V_PRECO * P_QUANTIDADE;

    UPDATE PRODUTO
    SET QUANTIDADE = QUANTIDADE + P_QUANTIDADE
    WHERE PRODUTOID = P_PRODUTOID;

    INSERT INTO MOVIMENTACAO_FINANCEIRA(VALOR, DESCRICAO, TIPO)
    VALUES (V_VALOR_TOTAL, CONCAT('COMPRA DE ', V_NOME), 'SAIDA');
END//

DELIMITER ;

