CREATE DATABASE SENTRY;
USE SENTRY;





CREATE TABLE USUARIO(
EMAIL VARCHAR(255) PRIMARY KEY
);


CREATE TABLE ARMAZENAMENTO(
ARMAZENAMENTOID INTEGER PRIMARY KEY,
NOME VARCHAR(255) NOT NULL,
USUARIO_EMAIL VARCHAR(255),
CONSTRAINT FK_USUARIO_EMAIL FOREIGN KEY (USUARIO_EMAIL) REFERENCES USUARIO(EMAIL)
);


CREATE TABLE PRODUTO(
PRODUTOID INTEGER PRIMARY KEY,
NOME VARCHAR(255) NOT NULL,
VALIDADE DATE NOT NULL,
QUANTIDADE FLOAT,
UNIDADE INTEGER,
ARMAZENAMENTOID INTEGER,
CONSTRAINT FK_ARMAZENAMENTOID FOREIGN KEY (ARMAZENAMENTOID) REFERENCES ARMAZENAMENTO(ARMAZENAMENTOID)
);



CREATE TABLE MOVIMENTACAO_FINANCEIRA(
MOVIMENTACAOID INTEGER PRIMARY KEY AUTO_INCREMENT,
VALOR FLOAT NOT NULL,
DESCRICAO VARCHAR(255),
TIPO ENUM('ENTRADA', 'SAIDA') NOT NULL,
DATA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



DELIMITER //
CREATE TRIGGER TR_ESTOQUE_MINIMO
BEFORE UPDATE ON PRODUTO
FOR EACH ROW
BEGIN
IF NEW.QUANTIDADE < 0 THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ESTOQUE INSUFICIENTE';
END IF;
END//



CREATE PROCEDURE SP_MOVIMENTAR_ESTOQUE(
IN P_PRODUTOID INTEGER,
IN P_QUANTIDADE FLOAT
)



BEGIN
UPDATE PRODUTO
SET QUANTIDADE = QUANTIDADE + P_QUANTIDADE
WHERE PRODUTOID = P_PRODUTOID;
END//



CREATE PROCEDURE SP_ITENS_MAIS_SAIDAS()
BEGIN
SELECT NOME, QUANTIDADE
FROM PRODUTO
WHERE QUANTIDADE < 5
ORDER BY QUANTIDADE ASC;
END//



CREATE PROCEDURE SP_MAIORES_GASTOS()
BEGIN
SELECT DESCRICAO, VALOR
FROM MOVIMENTACAO_FINANCEIRA
WHERE TIPO = 'SAIDA'
ORDER BY VALOR DESC;
END//



CREATE PROCEDURE SP_PRODUTOS_MAIS_CONSUMIDOS()
BEGIN
SELECT P.NOME, A.NOME AS LOCAL_ARMAZENAMENTO
FROM PRODUTO P
JOIN ARMAZENAMENTO A ON P.ARMAZENAMENTOID = A.ARMAZENAMENTOID
ORDER BY P.QUANTIDADE ASC;
END//



DELIMITER ;